branches:
  only:
    - /\d+\.\d+\.\d+/
    - matrix
language: python
python: "3.6"
env:
  global:
    - ADDON_ID=service.subtitles.rvm.addic7ed
jobs:
  include:
    - if: tag IS present
      env: BRANCH=krypton
    - if: branch = matrix
      env: BRANCH=matrix
install:
  - pip install -q kodi-addon-checker
script:
  - kodi-addon-checker --branch $BRANCH $ADDON_ID
before_deploy:
  - pip install -q git+https://github.com/xbmc/kodi-addon-submitter.git
  - submit-addon -s -z $ADDON_ID
  - export RELEASE_ZIP=$(ls *.zip)
deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: $RELEASE_ZIP
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: submit-addon -r repo-scripts -b $BRANCH -s -m --pull-request $ADDON_ID
    on:
      tags: true
  # This is used to submit only to matrix branch
  - provider: script
    script: submit-addon -r repo-scripts -b $BRANCH -s --pull-request $ADDON_ID
    on:
      branch: matrix
notifications:
  email: false
